spring:
   datasource:
      url: jdbc:mysql://localhost:3307/fornecedor?useTimezone=true&serverTimezone=UTC
      username: root
      password: root
   jpa:
      hibernate:
         ddl-auto: update
